version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql_container
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=finance-ai
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql
volumes:
  postgresql_data: